### ISSUE TITLE
Docker image build does not recurse git submodules

### ISSUE THREAD

**Issue by ancker010** [neggles/sd-webui-docker#1]
https://github.com/neggles/sd-webui-docker/blob/d29993ad5ab609651ee40d4c43c0dd9e84854c0c/docker/Dockerfile#L165

I think you need to add `--recurse-submodules` here when cloning the VLAD WebUI.
He includes a bunch of extensions by default that aren't getting cloned properly using your Dockerfile.

**Comment by neggles** [comment]
that would explain some things. I thought it was meant to pull those itself on first startup 😅 I'll add that in.

**Comment by neggles** [comment]
Should be fixed in a20b2d04865a07e9e53612e3675e3294af3f5b8c - try with the container image output from https://github.com/neggles/sd-webui-docker/actions/runs/4842300118/jobs/8629160153 (should have tag `vlad-59b51f2` once built) and let me know if it's still broken :)

I'll give it a try myself when I get a chance as well.

**Comment by ancker010** [comment]
This is fixed, in case you didn't end up testing it yourself.

Do you plan to build the Vlad image a little more often?

**Comment by neggles** [comment]
> This is fixed, in case you didn't end up testing it yourself.
> 
> Do you plan to build the Vlad image a little more often?

I did actually test it myself, then forgot to comment 😅 and yes, I've merged the scheduled builds :) probably shouldn't be running builds for the "stable" images daily, but, details.
